# -*- coding: utf-8 -*-
"""criptografia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UnK8Aaun5lpG7e62MovjwCJqimFnl66K
"""

import numpy

impar = 0 #caso a palavra inserida for ímpar, o valor é alterado para retirar na descriptografia a letra fictícia adicionada

#criptografando

#definindo a chave para criptografia
chave = numpy.array([[5, 10], [12, 3]])

#dicionário para relacionar letras e números (A=0, B=1, etc...)
alfabeto = {chr(i): i - ord('A') for i in range(ord('A'), ord('Z') + 1)}

#recebendo a palavra do usuário
palavra = input("Digite a palavra que será criptografada: ")

#verificar se foi passado algum valor
if(len(palavra) == 0):
    print("Palavra muito pequena")
elif(len(palavra) % 2 != 0):
    palavra += 'X' #adiciona X ao  final caso  a palavra seja ímpar
    impar+=1

#dividindo o  valor inserido em "palavra" em conjuntos de 2 letras
conjunto = []
for i in range(0, len(palavra), 2):
      conjunto.append(palavra[i:i+2])

#convertendo as letras para seus correspondentes numéricos
conjunto_num = []
for dupla in conjunto:
    num_dupla = [alfabeto[letra.upper()] for letra in dupla]
    conjunto_num.append(num_dupla)

#transformando os conjuntos em matrizes 2x1
conjunto_matrizes = []
for dupla_num in conjunto_num:
    matriz_2x1 = numpy.array(dupla_num).reshape(2, 1)
    conjunto_matrizes.append(matriz_2x1)

#multiplicando as matrizes pela matriz chave
conjunto_cripto = []
for matriz_bloco in conjunto_matrizes:
  matriz_result = numpy.dot(chave, matriz_bloco) % 26 #aplica a operação de módulo de 26 para q os resultados voltem para valores dentro do alfabeto
  conjunto_cripto.append(matriz_result)

#transformando os resultados em letras dnv
conjunto_letras = []
for matriz_conv in conjunto_cripto:
  letras_conv = ''.join([chr(i + ord('A')) for i in matriz_conv.flatten()])
  conjunto_letras.append(letras_conv)

#montando de volta em uma palavra
palavra_cripto = ""

for dupla in conjunto_letras:
  palavra_cripto += dupla

print("Palavra criptografada: ", palavra_cripto)

#descriptografando

#calculando determinante da matriz chave em modulo 26
det = int(round(numpy.linalg.det(chave))) #determinante em numero inteiro
det_mod = det % 26 #determinante em mod 26

#calculando a matriz adjunta da chave
chave_adjunta = numpy.array([[chave[1,1], -chave[0,1]], [-chave[1,0], chave[0,0]]])

#multiplicando pela inversa modular do determinante (que é 1 pq det%26 da resto 1, ou seja, det e 26 são coprimos)
chave_inversa_modular = (chave_adjunta * det_mod) % 26 #aplicando mod 26 para cada elemento

#multiplicando o texto cifrado contido em "conjunto_cripto" pela chave inversa (mesma operação de criptografar só q com outra matriz chave)
conjunto_decripto = []
for matriz_cripto in conjunto_cripto:
    matriz_result_decripto = numpy.dot(chave_inversa_modular, matriz_cripto) % 26
    conjunto_decripto.append(matriz_result_decripto)

#transformando em letras novamente
conjunto_letras_decripto = []
for matriz_decripto in conjunto_decripto:
    letras_decripto = ''.join([chr(i + ord('A')) for i in matriz_decripto.flatten()])
    conjunto_letras_decripto.append(letras_decripto)

#juntando em uma palavra
palavra_decripto = ""
for dupla_decripto in conjunto_letras_decripto:
    palavra_decripto += dupla_decripto

#retirando o X no final da palavra para o caso das palavras ímpares
if(impar != 0):
    palavra_decripto = palavra_decripto[:-1]

#exibindo
print("Palavra criptografada: ", palavra_cripto)
print("Palavra descriptografada: ", palavra_decripto)